### ISSUE TITLE
wildcard in topic

### ISSUE THREAD

**Issue by riksnelders** [KSDaemon/wampy.js#61]
Using crossbar. 

Want to subscribe with wildcard like topic.uri..live
as described in crossbar docs. Yes, the double dots are the wildcard.

Is this possible?

**Comment by KSDaemon** [comment]
Hi @riksnelders ! Sorry for delayed answer, i was on vocation.
Well, that is a useful feature. But right now it is not available in current release. I have a plans to implement it soon.
BTW, you can also help with that ;) If you have time, will and possibility.

**Comment by riksnelders** [comment]
Hey @KSDaemon. It sure is a usefull feature. I wouldnt have to loop for multiple devices to subscribe that are publishing on the same uri for example :).

I will try to add whenever I've got some time ! Keep me posted  on this!
Currently using wampy for frontend and autobahn for backend because of the wildcard option .

**Comment by KSDaemon** [comment]
Sure! 
I'll add references in commit messages to this issue (if i do not forget :)) )
Btw, you mean, wampy.js on client (browser) side, and autobahn.js on server (node.js) side?

**Comment by riksnelders** [comment]
Yes @KSDaemon. Simply because there will be tons of devices spamming data.
So instead of letting them send their id etc. the url contains the id, and since autobahn can use it, i can just extract the id from the uri using the wildcard.

Also, the reason why i use wampy for the front end is because autobahn didnt seem to work on an android device using fully kiosk :)

**Comment by KSDaemon** [comment]
Great! :)

**Comment by KSDaemon** [comment]
Done it! :)

**Comment by riksnelders** [comment]
Could u add this to the docs? I assume the wildcard is  the  double dots? com.uri..awesome ?

**Comment by riksnelders** [comment]
Hi KSDaemon,
Still not clear to me how to use the wildcard. Got an example?

**Comment by KSDaemon** [comment]
Hi @riksnelders !
You can a have a look at tests. But here is quick example:
```
wampy.subscribe('subscribe..wildcard', function (e) { /*ur callback */ }, { match: 'wildcard' })

wampy.subscribe('subscribe.prefix', function (e) { /*ur callback */ }, { match: 'prefix' })

```

**Comment by KSDaemon** [comment]
And yep! You are right! I'll add it to docs.

**Comment by riksnelders** [comment]
Thanks. Well done by the way!

**Comment by KSDaemon** [comment]
Thanks! :)
